export const farmers = [
  {
    id: 1,
    name: "Harsh Hardasani",
    image:
      "https://t4.ftcdn.net/jpg/06/30/06/81/360_F_630068155_RnZI6mC91wz7gUYFVmhzwpl4O6x00Cbh.jpg",
    primaryCrop: ["Wheat", "Soybean"],
    location: "Asangaon, Maharashtra",
    experience: 12,
    disputes: 1,
    contracts: 18,
    kyc: "Verified",
    phone: "9876543210",
    email: "harsh.patil@gmail.com",
  },
  {
    id: 2,
    name: "Ramesh Singh",
    image:
      "https://www.shutterstock.com/image-photo/portrait-old-hindu-man-white-260nw-2433714111.jpg",
    primaryCrop: ["Rice", "Wheat"],
    location: "Ludhiana, Punjab",
    experience: 8,
    disputes: 0,
    contracts: 11,
    kyc: "Verified",
    phone: "9812345678",
    email: "ramesh.singh@gmail.com",
  },
  {
    id: 3,
    name: "Aniket More",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSaFhD8K7GsilnOX2NsjjG7etJM86IAhHn6ZQ&s",
    primaryCrop: ["Wheat", "Mustard"],
    location: "Rewari, Haryana",
    experience: 15,
    disputes: 2,
    contracts: 25,
    kyc: "Verified",
    phone: "9823456781",
    email: "amit.yadav@gmail.com",
  },
  {
    id: 4,
    name: "Kunal Nemade",
    image: "https://randomuser.me/api/portraits/men/48.jpg",
    primaryCrop: ["Cotton", "Groundnut"],
    location: "Rajkot, Gujarat",
    experience: 6,
    disputes: 1,
    contracts: 9,
    kyc: "Pending",
    phone: "9898989898",
    email: "suresh.verma@gmail.com",
  },
  {
    id: 5,
    name: "Rahul Mishra",
    image:
      "https://static.vecteezy.com/system/resources/thumbnails/055/153/327/small/portrait-of-a-farmer-with-crop-over-shoulder-in-a-lush-green-field-free-photo.jpeg",
    primaryCrop: ["Sugarcane", "Wheat"],
    location: "Rampur, Uttar Pradesh",
    experience: 20,
    disputes: 0,
    contracts: 32,
    kyc: "Verified",
    phone: "9797979797",
    email: "rahul.mishra@gmail.com",
  },

  {
    id: 6,
    name: "Mahesh Jadhav",
    image:
      "https://garhwalpost.in/wp-content/uploads/2022/03/Pankaj-Tripathi.jpg",
    primaryCrop: ["Jowar", "Bajra"],
    location: "Solapur, Maharashtra",
    experience: 16,
    disputes: 1,
    contracts: 20,
    kyc: "verified",
    phone: "9012345678",
    email: "mahesh.j@gmail.com",
  },

  {
    id: 9,
    name: "Sunil Pawar",
    image: "https://randomuser.me/api/portraits/men/69.jpg",
    primaryCrop: ["Onion", "Tomato"],
    location: "Nashik, Maharashtra",
    experience: 14,
    disputes: 2,
    contracts: 20,
    kyc: "Verified",
    phone: "9988776655",
    email: "sunil.p@gmail.com",
  },
  {
    id: 10,
    name: "Adarsh Mishra",
    image: "https://randomuser.me/api/portraits/men/58.jpg",
    primaryCrop: ["Paddy", "Chilli"],
    location: "Guntur, Telangana",
    experience: 11,
    disputes: 0,
    contracts: 17,
    kyc: "Verified",
    phone: "9654321870",
    email: "vikram.reddy@gmail.com",
  },

  {
    id: 11,
    name: "Anil Naik",
    image: "https://thumbs.dreamstime.com/b/old-man-portrait-17998373.jpg",
    primaryCrop: ["Cashew", "Coconut"],
    location: "Ratnagiri, Maharashtra",
    experience: 18,
    disputes: 1,
    contracts: 22,
    kyc: "Verified",
    phone: "9871203456",
    email: "anil.naik@gmail.com",
  },
  {
    id: 12,
    name: "Rohit Thakur",
    image: "https://randomuser.me/api/portraits/men/50.jpg",
    primaryCrop: ["Apple", "Maize"],
    location: "Shimla, Himachal",
    experience: 13,
    disputes: 0,
    contracts: 19,
    kyc: "Verified",
    phone: "9890011223",
    email: "rohit.thakur@gmail.com",
  },
  {
    id: 14,
    name: "Prakash Gowda",
    image:
      "https://static.vecteezy.com/system/resources/thumbnails/059/278/109/small/smiling-farmer-in-lush-green-fields-rural-india-portraitgraphy-natural-background-close-up-view-agricultural-life-concept-free-photo.jpeg",
    primaryCrop: ["Coffee", "Pepper"],
    location: "Coorg, Karnataka",
    experience: 21,
    disputes: 0,
    contracts: 30,
    kyc: "Verified",
    phone: "9445566778",
    email: "prakash.g@gmail.com",
  },
  {
    id: 15,
    name: "Sanjay Das",
    image:
      "https://t3.ftcdn.net/jpg/17/72/23/36/360_F_1772233678_xAqplYbpg8dTZI0wbL41mREtyPEFt8wU.jpg",
    primaryCrop: ["Rice", "Jute"],
    location: "Hooghly, Bengal",
    experience: 17,
    disputes: 1,
    contracts: 24,
    kyc: "Pending",
    phone: "9834455667",
    email: "sanjay.das@gmail.com",
  },

  /* ----------- extra farmers to reach 35 ----------- */
];
